<Project>
  <PropertyGroup>

    <!-- Target framework -->
    <TargetFramework>net10.0</TargetFramework>

    <!-- Compiler -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Documentation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Build behavior -->
    <Deterministic>true</Deterministic>

  </PropertyGroup>
</Project>

